server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    access_log /var/log/nginx/access.log combined;

    server_tokens off;
    add_header X-Powered-By "PHP/7.4" always;
    add_header X-Backend-Server "intranet-web-01" always;
    add_header X-Decoy-Server "Apache/2.4.49" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /login {
        try_files /login.html =404;
    }

    location = /support {
        try_files /support.html =404;
    }

    location = /status {
        try_files /status.html =404;
    }

    location = /docs {
        try_files /docs.html =404;
    }
}
